"""topic instructions model update

Revision ID: 3e99c69673d6
Revises: c4dd57625ea9
Create Date: 2025-11-23 16:30:23.132603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e99c69673d6'
down_revision: Union[str, Sequence[str], None] = 'c4dd57625ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_instruction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_topic_instruction_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_instruction'))
    )
    op.drop_table('topic_instructions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_instructions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_topic_instructions_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_instructions'))
    )
    op.drop_table('topic_instruction')
    # ### end Alembic commands ###
