"""add_amms_tables

Revision ID: 43c445a56473
Revises: 3e99c69673d6
Create Date: 2026-03-07 14:32:16.403600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '43c445a56473'
down_revision: Union[str, Sequence[str], None] = '3e99c69673d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snaap_ribbonways',
    sa.Column('rbn_id', sa.UUID(), nullable=False),
    sa.Column('rbn_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rbn_name', sa.String(), nullable=True),
    sa.Column('rbn_description', sa.Text(), nullable=True),
    sa.Column('rbn_geofence_location', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('rbn_id', name=op.f('pk_snaap_ribbonways'))
    )
    op.create_table('snaap_riders',
    sa.Column('rdr_id', sa.UUID(), nullable=False),
    sa.Column('rdr_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rdr_first_name', sa.String(), nullable=True),
    sa.Column('rdr_last_name', sa.String(), nullable=True),
    sa.Column('rdr_email', sa.String(), nullable=True),
    sa.Column('rdr_phone_number', sa.String(), nullable=True),
    sa.Column('rdr_password', sa.String(), nullable=True),
    sa.Column('rdr_avatar', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('rdr_id', name=op.f('pk_snaap_riders'))
    )
    op.create_table('snaap_pods',
    sa.Column('pod_id', sa.UUID(), nullable=False),
    sa.Column('pod_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pod_name', sa.String(), nullable=True),
    sa.Column('pod_description', sa.Text(), nullable=True),
    sa.Column('pod_configuration', sa.String(), nullable=True),
    sa.Column('pod_current_status', sa.String(), nullable=True),
    sa.Column('pod_current_location', sa.String(), nullable=False),
    sa.Column('rbn_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['rbn_id'], ['snaap_ribbonways.rbn_id'], name=op.f('fk_snaap_pods_rbn_id_snaap_ribbonways')),
    sa.PrimaryKeyConstraint('pod_id', name=op.f('pk_snaap_pods'))
    )
    op.create_table('snaap_ribbonway_portals',
    sa.Column('ptl_id', sa.UUID(), nullable=False),
    sa.Column('ptl_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ptl_name', sa.String(), nullable=True),
    sa.Column('ptl_description', sa.Text(), nullable=True),
    sa.Column('ptl_geofence_location', sa.JSON(), nullable=True),
    sa.Column('rbn_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['rbn_id'], ['snaap_ribbonways.rbn_id'], name=op.f('fk_snaap_ribbonway_portals_rbn_id_snaap_ribbonways')),
    sa.PrimaryKeyConstraint('ptl_id', name=op.f('pk_snaap_ribbonway_portals'))
    )
    op.create_table('snaap_portal_docks',
    sa.Column('dck_id', sa.UUID(), nullable=False),
    sa.Column('dck_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dck_name', sa.String(), nullable=True),
    sa.Column('dck_description', sa.Text(), nullable=True),
    sa.Column('dck_geofence_location', sa.JSON(), nullable=True),
    sa.Column('ptl_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ptl_id'], ['snaap_ribbonway_portals.ptl_id'], name=op.f('fk_snaap_portal_docks_ptl_id_snaap_ribbonway_portals')),
    sa.PrimaryKeyConstraint('dck_id', name=op.f('pk_snaap_portal_docks'))
    )
    op.create_table('snaap_ride_requests',
    sa.Column('rde_id', sa.UUID(), nullable=False),
    sa.Column('rde_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rde_boarding_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('rde_dropoff_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('rde_amount_charged', sa.Numeric(), nullable=True),
    sa.Column('rde_currency_charged', sa.String(), nullable=True),
    sa.Column('rdr_id', sa.UUID(), nullable=True),
    sa.Column('ptl_id', sa.UUID(), nullable=True),
    sa.Column('pod_id', sa.UUID(), nullable=True),
    sa.Column('rde_starting_dock', sa.UUID(), nullable=True),
    sa.Column('rde_ending_dock', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pod_id'], ['snaap_pods.pod_id'], name=op.f('fk_snaap_ride_requests_pod_id_snaap_pods')),
    sa.ForeignKeyConstraint(['ptl_id'], ['snaap_ribbonway_portals.ptl_id'], name=op.f('fk_snaap_ride_requests_ptl_id_snaap_ribbonway_portals')),
    sa.ForeignKeyConstraint(['rdr_id'], ['snaap_riders.rdr_id'], name=op.f('fk_snaap_ride_requests_rdr_id_snaap_riders')),
    sa.PrimaryKeyConstraint('rde_id', name=op.f('pk_snaap_ride_requests'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snaap_ride_requests')
    op.drop_table('snaap_portal_docks')
    op.drop_table('snaap_ribbonway_portals')
    op.drop_table('snaap_pods')
    op.drop_table('snaap_riders')
    op.drop_table('snaap_ribbonways')
    # ### end Alembic commands ###
